# This file is a template, and might need editing before it works on your project.
# Official Java image. Look for the different tagged releases at
# https://hub.docker.com/r/library/java/tags/ . A Java image is not required
# but an image with a JVM speeds up the build a bit.
image: java:8

before_script:
  - echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
  - sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
  # Enable the usage of sources over https
  #- apt-get update -yqq
  - apt-get -o Acquire::Check-Valid-Until=false update -yqq
  - apt-get install apt-transport-https unzip -yqq
  # Add keyserver for SBT
  - echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  # Install SBT
  #- apt-get update -yqq
  - apt-get -o Acquire::Check-Valid-Until=false update -yqq
  - apt-get install sbt -yqq
  # Log the sbt version
  - sbt version

test:
  script:
    # Execute your project's tests
    - sbt clean test
  artifacts:
    reports:
      junit: target/test-reports/*.xml